apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "urlshortener.fullname" . }}-config
data:
  DATABASE_NAME: {{ .Values.postgresql.postgresqlDatabase | quote }}
  DATABASE_USER: {{ .Values.postgresql.postgresqlUsername | quote }}
  DATABASE_PORT: {{ .Values.postgresql.service.port | quote }}
  DATABASE: postgres
  WAIT_FOR_IT_TIMER: {{ .Values.image.waitForItTimeout | quote }}
{{- if .Values.postgresql.enabled }}
  DATABASE_HOST: {{ include "urlshortener.postgresql.fullname" . | quote }}
{{- else }}
  DATABASE_HOST: {{ .Values.postgresql.service.host | quote }}
{{- end }}
